openapi: 3.0.3
info:
    title: Goa API
    version: "1.0"
servers:
    - url: http://localhost:80
      description: Default server for Example
paths:
    /example:
        post:
            tags:
                - FooService
            summary: FooMethod FooService
            operationId: FooService#FooMethod
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: array
                            items:
                                $ref: '#/components/schemas/ExampleType'
                            example:
                                - External:
                                    Field: Nisi molestiae suscipit voluptates voluptates.
                                - External:
                                    Field: Nisi molestiae suscipit voluptates voluptates.
                        example:
                            - External:
                                Field: Nisi molestiae suscipit voluptates voluptates.
                            - External:
                                Field: Nisi molestiae suscipit voluptates voluptates.
                            - External:
                                Field: Nisi molestiae suscipit voluptates voluptates.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/ExampleType'
                                example:
                                    - External:
                                        Field: Quasi ut mollitia id similique facilis corrupti.
                                    - External:
                                        Field: Quasi ut mollitia id similique facilis corrupti.
                                    - External:
                                        Field: Quasi ut mollitia id similique facilis corrupti.
                                    - External:
                                        Field: Quasi ut mollitia id similique facilis corrupti.
                            example:
                                - External:
                                    Field: Quasi ut mollitia id similique facilis corrupti.
                                - External:
                                    Field: Quasi ut mollitia id similique facilis corrupti.
                                - External:
                                    Field: Quasi ut mollitia id similique facilis corrupti.
components:
    schemas:
        ExampleType:
            type: object
            properties:
                External:
                    $ref: '#/components/schemas/ExternalType'
            example:
                External:
                    Field: Nisi molestiae suscipit voluptates voluptates.
        ExternalType:
            type: object
            properties:
                Field:
                    type: string
                    example: Eum voluptatem et blanditiis tempora.
            example:
                Field: Laborum illo distinctio rerum quisquam.
            required:
                - Field
tags:
    - name: FooService
